name: Deploy Kamra Kiraya

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Push Database Schema
        run: npx prisma db push --skip-generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Next.js App
        run: npm run build
        env:
          DATABASE_URL: ${{postgresql://postgres.wmfibigtcaxtedfhehcx:%40Forstudents013@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
}}
          JWT_SECRET: ${{ c8f2a9e1b4d7f3a6e0c5b8d2f1a4e7c9b3d6f0a2c5e8b1d4f7a0c3e6b9d2f5a8 }}
          UPI_ID: ${{ 8209184926@axl }}
          UPI_NAME: ${{ Kamra Kiraya }}
          UPI_NOTE: ${{ secrets.UPI_NOTE }}
          NEXT_PUBLIC_UPI_ID: ${{ secrets.NEXT_PUBLIC_UPI_ID }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          GEMINI_API_KEY: ${{ AQ.Ab8RN6JdYBe_M0nRFJG6QJzVhg1AzB5BOh6pGnw4_JyDpXgc6A }}
          GEMINI_MODEL: "gemini-2.0-flash"
